name: GNTL Electron Wallet Build for macOS
on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
              os: [macos-11]

        steps:
            - name: Check-out Repo
              uses: actions/checkout@v1

            - name: Install Node
              uses: actions/setup-node@v1
              with:
                node-version: "12.20.2"

            - name: Install Dependencies
              run: npm install -f

            - name: Download latest GNTL Release
              run: node ./build/download-binaries.js
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract Binaries (Tar)
              run: tar -xf latest.gz
              shell: bash
              working-directory: ./downloads

            - name: Move Daemon and Wallet Binaries
              run: |
                find ./downloads -type f -name "gntld*" -exec cp '{}' ./bin \;
                find ./downloads -type f -name "gntl-wallet-rpc*" -exec cp '{}' ./bin \;
              shell: bash

            - name: Verify Binaries
              run: ls ./bin
              shell: bash

            - name: Publish Binaries
              run: npm run build
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                CSC_LINK: ${{ secrets.MAC_CERTIFICATE }}
                CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
                ELECTRON_WALLET_APPLE_ID: ${{ secrets.ELECTRON_WALLET_APPLE_ID }}
                ELECTRON_WALLET_PASSWORD: ${{ secrets.ELECTRON_WALLET_PASSWORD }}
                ELECTRON_WALLET_TEAM_ID: ${{ secrets.ELECTRON_WALLET_TEAM_ID }}

            - name: Remove un-needed Artifacts
              run: rm -r -- ./*/
              shell: bash
              working-directory: ./dist/electron-mat/Packaged
              
            - name: Upload Artifacts
              uses: actions/upload-artifact@v1
              with:
                name: ${{ runner.OS }}
                path: dist/electron-mat/Packaged
