name: GNTL Electron Wallet Build
on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
              os: [windows-2016]

        steps:
            - name: Checkout git repo
              uses: actions/checkout@v1

            - name: Install node
              uses: actions/setup-node@v1
              with:
                node-version: "12.20.2"

            - name: Install dependencies
              run: npm install -f

            - name: Download Gntld binaries
              run: node ./build/download-binaries.js

            - name: Extract 7z binaries
              run: 7z x latest.7z
              shell: bash
              working-directory: ./downloads

            - name: Move gntld binaries
              run: |
                find ./downloads -type f -name "gntld*" -exec cp '{}' ./bin \;
                find ./downloads -type f -name "gntl-wallet-rpc*" -exec cp '{}' ./bin \;
              shell: bash

            - name: Verify binaries
              run: ls ./bin
              shell: bash

            - name: Publish window binaries
              run: npm run build
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Remove un-needed artifacts
              run: rm -r -- ./*/
              shell: bash
              working-directory: ./dist/electron-mat/Packaged

            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                name: ${{ runner.OS }}
                path: dist/electron-mat/Packaged
